<a href="https://colab.research.google.com/github/kellisfm/100_days_of_code_challange/blob/master/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.18.5


##exercises:
create a numpy array of size 10, filled with 0s

create an array with values ranging from 10 to 49

create a matrix of 2x2 integers, filled with ones

create a numpy matrix of 3x2 floats, filled with ones

given the x numpy array, create a new array with the same size, shape and type as x, filled with 1s

given x numpy array, create a new matrix with the same shape and type filled with 0s

create matrix of 4x4 filled with fives

given x create a new matrix with shame type/shape filled with sevens

create a 3x3 identity numpy matrixs with ones on the diagonal and 0s elsewhere

create a numpy array filled with 3 random values between 1 and 10

create a 3x3x3 numpy matrix filled with random floats

given list x convert to a y numpy array

given x make a copy and store on y

create a numpy array with the number 1-10

create a numpy array with the odds 1-10

1-10 descending

3x3 with values ranging 0-8

show memory size of the given z numpy matrix



In [ ]:
#x array referenced in multiple questions

X = np.arange(4, dtype=np.int)

In [ ]:
#10 0s
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#values ranging from 10-49
np.arange(10,50) #end 1 higher than needed

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#2x2 integers, filled with 1s
np.ones([2,2],dtype = int)

array([[1, 1],
       [1, 1]])

In [ ]:
#3x2 floats, ones
np.ones([3,2],dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.ones_like(X) #array of same type and shape as x, but with only ones
np.zeros_like(X) #array of same type/shape, but with 0s
np.ones_like(X)*7 #same type shape, but with 7s

array([7, 7, 7, 7])

In [ ]:
np.ones([5,5])*5 #5x5 array of 5s

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
np.identity(3) #identity creates square array with 1s on diagonal, useful for round robin type charts?

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(10,size = 3) #random integers

array([0, 5, 8])

In [ ]:
np.random.randn(3,3,3) #generates random numbers from a normal distribution with sd 1, centered on 0

array([[[ 1.21725396,  0.53372265,  0.4495021 ],
        [ 0.37071803, -0.48777229, -0.79307813],
        [ 0.87030636,  0.3838547 ,  0.44259526]],

       [[ 0.81079013, -0.70307169, -0.43791901],
        [ 1.24151389,  0.27976102, -0.07689512],
        [ 0.51865382, -0.57101271, -0.21927165]],

       [[ 0.30725386,  1.06849563, -1.22954512],
        [-1.03207691,  1.35071129,  0.45093764],
        [-1.37614606, -1.09139257,  1.33415842]]])

In [ ]:
np.array(X) #converts list to array
np.copy(X) #makes a copy that can be edited independantly from the OG

array([0, 1, 2, 3])

In [ ]:
np.arange(1,11) #1-10 
np.arange(1,11,2) #only odds
np.arange(1,11)[::-1] #prints in reverse order
np.arange(9).reshape(3,3) #reshape converts the row,col of interest

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
print("%d bytes"%(X.size *X.itemsize)) #prints req memory of the object x in bytes

32 bytes


## array indexing


In [ ]:
#given x show first element:
X[0]
#show last element:
X[-1]
#show first three elements:
X[:3] #remember it doesnt show the last element
#show all middle elements:
X[1:-1]
#show in reverse:
X[::-1]
#show odd elements
X[::2]


array([0, 2])

In [ ]:
#given x, show first row
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0][:]
#show last row
X[-1]
#fe, fr
X[0,0]
#le,lr
X[-1,-1]
#middle row and column elements
X[1:-1,1:-1]
#first 2 ele, 2 row
X[:2,:2]
#last 2 ele, last 2 row
X[-2:,-2:]

array([[11, 12],
       [15, 16]])

## array manipulation

In [63]:
#reverse the array
x = (X)[::-1,::-1] # ::-1 swaps order, repeat for number of dimensions
print(x)

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [60]:
np.array(X,np.float)#convert to float, can't just float have to rearray as a float

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [65]:
x.sort() #sorts each individual list, but doesnt sort higher dimensions
print(x)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [70]:
#convert 3rd element to 1s
x[2] = 1
print(x)
#lr li to 0
x[-1,-1] = 0 #NOT [x][x], use [x,x]
#add 5 to each element
x+5

[[13 14 15 16]
 [ 9 10 11 12]
 [ 1  1  1  1]
 [ 1  2  3  0]]


array([[18, 19, 20, 21],
       [14, 15, 16, 17],
       [ 6,  6,  6,  6],
       [ 6,  7,  8,  5]])

##boolean arrays

In [82]:
#given x make a mask showing only negative elements:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X[X<0]

#get numbers higher than 5
X[X>5]
#numbers larger than the mean
mask = X > X.mean()
X[mask]
#numbers equal to 2 or 10
mask = (X == 10) | (X == 2)
print(mask,X)
X[mask]

[False  True False False False False False False False  True] [-1  2  0 -4  5  6  0  0 -9 10]


array([ 2, 10])

In [86]:
#return true if none of the elements are 0
X.all()
#return true if any of the elements are 0
X.any()

True